[project]
name = "quick-excel-csv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.15"
dependencies = [
    "pandas>=3.0.6",
    "rich>=15.0.0",
    "textual>=8.2.8",
    "textual-dev>=1.8.0",
]
